# **Mức Dễ**

## 1. Tạo vector `x` gồm các số từ 1 đến 10. Tính tổng, hiệu, tích và thương của tất cả phần tử với số 2.

In [1]:
x <- 1:10
print(x + 2)
print(x - 2)
print(x * 2)
print(x / 2)

 [1]  3  4  5  6  7  8  9 10 11 12
 [1] -1  0  1  2  3  4  5  6  7  8
 [1]  2  4  6  8 10 12 14 16 18 20
 [1] 0.5 1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0



---
2. Cho vector `a <- c(TRUE, FALSE, TRUE)` và `b <- c(FALSE, TRUE, TRUE)`. Tính `a & b`, `a | b` và `!a`.

In [2]:
a <- c(TRUE, FALSE, TRUE)
b <- c(FALSE, TRUE, TRUE)
print(a & b)
print(a | b)
print(!a)

[1] FALSE FALSE  TRUE
[1] TRUE TRUE TRUE
[1] FALSE  TRUE FALSE



---
3. Cho vector `x <- c(3, 7, 10, 15)`. Kiểm tra các phần tử nào lớn hơn 5, nhỏ hơn hoặc bằng 10, và bằng 7.

In [3]:
x <- c(3, 7, 10, 15)
print(x > 5)
print(x <= 10)
print(x == 7)

[1] FALSE  TRUE  TRUE  TRUE
[1]  TRUE  TRUE  TRUE FALSE


[1] FALSE  TRUE FALSE FALSE



---
4. Tạo vector `v <- c(5, 10, 15, 20, 25)`. Lấy phần tử thứ 2, phần tử cuối cùng, và loại bỏ phần tử thứ 3.

In [4]:
v <- c(5, 10, 15, 20, 25)
print(v[2])
print(v[5])
print(v[-3])

[1] 10


[1] 25
[1]  5 10 20 25



---
5. Cho `x <- c(1, 2, 3, 4)` và `y <- c(5, 6)`. Thực hiện phép cộng và phép nhân theo vector hóa.

In [5]:
x <- c(1, 2, 3, 4)
y <- c(5, 6)

print(x + y)
print(x * y)

[1]  6  8  8 10


[1]  5 12 15 24



---
6. Tạo một list chứa tên của bạn, tuổi và điểm trung bình môn R. Truy xuất từng phần tử từ list.

In [6]:
HTT <- list(
    name = "Hoang Tuan Tu",
    age = 22,
    GPA = 10.0
)

print(HTT$name)
print(HTT$age)
print(HTT$GPA)

[1] "Hoang Tuan Tu"
[1] 22


[1] 10



---
7. Tạo vector `colors <- c("red","blue","red","green","blue","green","red")`. sau đó tạo factor với vector đó

In [7]:
colors <- c("red", "blue", "red", "green", "blue", "green", "red")
colors_factor <- factor(colors)
print(colors_factor)

[1] red   blue  red   green blue  green red  
Levels: blue green red



---
8. Tạo ma trận 3x3 từ vector `c(1:9)`. Lấy phần tử hàng 2 cột 3, toàn bộ hàng 1, và cột 2 & 3.

In [8]:
matrix <- matrix(1:9, 3, 3)
print(matrix[2, 3])
print(matrix[1, ])
print(matrix[, 2:3])

[1] 8
[1] 1 4 7
     [,1] [,2]
[1,]    4    7
[2,]    5    8
[3,]    6    9



---
9. Tạo ma trận `A <- matrix(1:4, 2, 2)` và `B <- matrix(5:8, 2, 2)`. Thực hiện cộng, trừ, nhân theo từng phần tử và nhân ma trận.

In [9]:
A <- matrix(1:4, 2, 2)
B <- matrix(5:8, 2, 2)

print(A + B)
print(A - B)
print(A * B)
print(A %*% B)

     [,1] [,2]
[1,]    6   10
[2,]    8   12
     [,1] [,2]
[1,]   -4   -4
[2,]   -4   -4


     [,1] [,2]
[1,]    5   21
[2,]   12   32
     [,1] [,2]
[1,]   23   31
[2,]   34   46


---
10. Tạo vector số nguyên từ 1 đến 20.

* Chia vector thành hai vector: số chẵn và số lẻ.
* Tạo ma trận 2x5 từ vector số chẵn.
* Tính bình phương các phần tử ma trận.

In [10]:
# Tạo vector số nguyên từ 1 đến 20
v <- 1:20

# Chia thành số chẵn và số lẻ
even_conditition <- v %% 2 == 0
even <- v[even_conditition]
print(even)

odd_conditition <- v %% 2 != 0
odd  <- v[odd_conditition]
print(odd)

# Tạo ma trận 2x5 từ vector số chẵn
m <- matrix(even, nrow = 2)
print(m)

# Tính bình phương các phần tử ma trận
m_sq <- m^2
print(m_sq)

 [1]  2  4  6  8 10 12 14 16 18 20
 [1]  1  3  5  7  9 11 13 15 17 19
     [,1] [,2] [,3] [,4] [,5]
[1,]    2    6   10   14   18
[2,]    4    8   12   16   20
     [,1] [,2] [,3] [,4] [,5]
[1,]    4   36  100  196  324
[2,]   16   64  144  256  400
