# **Một số Phép toán trong R**

Trong R (và các ngôn ngữ lập trình khác), toán tử là những ký hiệu hoặc từ khóa đặc biệt dùng để thực hiện phép tính hay thao tác trên dữ liệu.

Nếu ví dụ ngoài đời:

* Dấu + là toán tử để cộng.
* Dấu - là toán tử để trừ.

Tương tự, trong R cũng có các toán tử như vậy, nhưng ngoài cộng, trừ còn có nhiều loại hơn.

## **Các phép toán cơ bản trong R**

* Phép cộng `+`:

In [1]:
123 + 234   # 357

[1] 357

* Phép trừ `-`:

In [2]:
3234 - 532 # 2702

[1] 2702

* Phép nhân `*`:

In [3]:
123 * 456   # 56088

[1] 56088

* Phép chia `/`:

In [4]:
100 / 25    # 4

[1] 4

* Lũy thừa `^`:

In [5]:
2 ^ 3       # 8

[1] 8

* Chia lấy phần nguyên `%/%`:

In [6]:
10 %/% 3    # 3

[1] 3

* Chia lấy phần dư `%%`:

In [7]:
10 %% 3     # 1

[1] 1

---

## **Các phép toán logic trong R**

* Toán tử **và** - `&&` hoặc `&`:

In [8]:
TRUE & FALSE    # FALSE
TRUE && FALSE   # FALSE

[1] FALSE

[1] FALSE

* Toán tử hoặc - `||` hoặc `|`:

In [9]:
TRUE | FALSE    # TRUE
TRUE || FALSE   # TRUE

[1] TRUE

[1] TRUE

* Phép phủ định `!`:

In [10]:
!TRUE   # FALSE
!FALSE  # TRUE

[1] FALSE

[1] TRUE


---

## **Các phép toán so sánh**

* So sánh bằng:

In [11]:
5 == 5   # TRUE
5 == 6   # FALSE

[1] TRUE

[1] FALSE

* Khác:

In [12]:
5 != 6   # TRUE

[1] TRUE

* Lớn hơn / Nhỏ hơn:

In [13]:
5 > 2    # TRUE
5 < 2    # FALSE

[1] TRUE

[1] FALSE

* Lớn hơn hoặc bằng / Nhỏ hơn hoặc bằng:

In [14]:
5 >= 5   # TRUE
4 <= 6   # TRUE

[1] TRUE

[1] TRUE

---

> Ngoại trừ toán tử `&&` và `||`, các toán tử khác trong R đều có tính **“vectơ hóa”** (vectorized). Ví dụ:

In [15]:
print(c(1, 2, 3) + c(4, 5, 6))   # 5 7 9
print(c(1, 2, 3) > c(0, 2, 5))   # TRUE FALSE FALSE

[1] 5 7 9
[1]  TRUE FALSE FALSE


# **Các kiểu dữ liệu trong R**

## **Biến và gán dữ liệu trong R**

Trong R, để gán giá trị cho một biến có thể dùng các toán tử `=` hoặc `<-` hoặc `->`.

Tên biến trong R phân biệt chữ hoa và chữ thường (`Var1` khác với `var1`).

In [16]:
x <- 10
y = 20
x + y -> z
print(z)

[1] 30



---

## **Logical**

Kiểu **logical** chỉ có hai giá trị: `TRUE` hoặc `FALSE`.

In [17]:
v <- TRUE
print(v)
print(class(v))   # "logical"

a <- (5 > 3)
print(a)          # TRUE

[1] TRUE
[1] "logical"
[1] TRUE


--- 

## **Numeric**

Kiểu **numeric** biểu diễn số thực (decimal). Đây là kiểu số mặc định trong R.

In [18]:
v <- 12.3
print(v)
print(class(v))   # "numeric"

[1] 12.3


[1] "numeric"



---

## **Integer**

Để khai báo số nguyên, thêm hậu tố `L` sau số.

In [19]:
v <- 10L
print(v)
print(class(v))   # "integer"

[1] 10
[1] "integer"



---

## **Complex**

Kiểu **complex** dùng để biểu diễn số phức với phần thực và phần ảo.

In [20]:
v <- 2 + 3i
print(v)
print(class(v))   # "complex"

[1] 2+3i
[1] "complex"



---

## **Character**

Kiểu **character** biểu diễn chuỗi ký tự.

In [21]:
v <- "Hello R"
print(v)
print(class(v))   # "character"

[1] "Hello R"
[1] "character"



---

## **Raw**

Kiểu **raw** biểu diễn dữ liệu thô dưới dạng mã hex.


In [22]:
# Tạo raw từ số
v <- as.raw(c(0x48, 0x65, 0x6c, 0x6c, 0x6f))
print(v)          # 48 65 6c 6c 6f
print(class(v))   # "raw"

# Chuyển raw về chuỗi
rawToChar(v)      # "Hello"

# Ngược lại: chuỗi sang raw
charToRaw("Hello")  # 48 65 6c 6c 6f

[1] 48 65 6c 6c 6f
[1] "raw"


[1] "Hello"

[1] 48 65 6c 6c 6f


---

# **Các cấu trúc dữ liệu trong R**

## **vector**

Là một mảng dùng để lưu trữ các dữ liệu có cùng kiểu với nhau. Để tạo một vector, ta sử dụng hàm `c()` hoặc sử dụng toán tử `:` (Đối với các phần tử là số nguyên liên tiếp)

In [23]:
# x là một vector
x <- c(1, 3, 5, 7, 8)
print(x)

y <- 1:9
print(y)

[1] 1 3 5 7 8
[1] 1 2 3 4 5 6 7 8 9


Để lấy giá trị một phần tử trong vector, ta sử dụng cú pháp sau:

In [24]:
print(x[2]) # 3
print(x[-1]) # 3 5 7 8
print(x[-c(1, 2, 3)]) # 7 8
print(x[c(TRUE, TRUE, FALSE, FALSE, TRUE)]) # 1 3 8
print(x[c(1, 2, 3, 4)])

[1] 3
[1] 3 5 7 8


[1] 7 8
[1] 1 3 8
[1] 1 3 5 7


Ta cũng có thể kết hợp 2 hoặc nhiều vector bằng cách sau:

In [25]:
a <- 1:3
b <- 4:6
c <- 9:11

v <- c(a, b, c)
print(v)

[1]  1  2  3  4  5  6  9 10 11


## Tính vector hóa trong R với các toán tử

Một đặc điểm mạnh mẽ của R là **các toán tử và hàm được vector hóa**. Nghĩa là ta có thể thực hiện phép toán trực tiếp trên toàn bộ vector mà không cần dùng vòng lặp.

### Ví dụ 1: Các phép toán cơ bản

In [26]:
x <- c(1, 2, 3, 4)
y <- c(10, 20, 30, 40)

print(x + y)   # [1] 11 22 33 44
print(x - y)   # [1]  -9 -18 -27 -36
print(x * y)   # [1]  10  40  90 160
print(x / y)   # [1] 0.1 0.1 0.1 0.1

[1] 11 22 33 44
[1]  -9 -18 -27 -36
[1]  10  40  90 160
[1] 0.1 0.1 0.1 0.1



---

### Ví dụ 2: Lũy thừa và chia lấy dư, chia lấy nguyên

In [27]:
x <- c(2, 4, 6)

print(x ^ 2)    # [1]  4 16 36
print(x %% 4)   # [1] 2 0 2
print(x %/% 4)  # [1] 0 1 1  (chia lấy phần nguyên)

[1]  4 16 36
[1] 2 0 2
[1] 0 1 1



---

### Ví dụ 3: Vector có độ dài khác nhau (recycling rule)

Khi hai vector có độ dài khác nhau, R sẽ lặp lại (recycle) phần tử của vector ngắn hơn:

In [28]:
x <- c(1, 2, 3, 4)
y <- c(10, 20)

print(x + y)    # [1] 11 22 13 24

[1] 11 22 13 24


Ở đây: `1+10, 2+20, 3+10, 4+20`

### Ví dụ 4: Toán tử so sánh trong R

In [29]:
x <- c(5, 10, 15)
y <- c(10, 10, 10)

print(x == y)   # [1] FALSE  TRUE FALSE
print(x != y)   # [1]  TRUE FALSE  TRUE
print(x >  y)   # [1] FALSE FALSE  TRUE
print(x >= y)   # [1] FALSE  TRUE  TRUE
print(x <  y)   # [1]  TRUE FALSE FALSE
print(x <= y)   # [1]  TRUE  TRUE FALSE


[1] FALSE  TRUE FALSE
[1]  TRUE FALSE  TRUE
[1] FALSE FALSE  TRUE
[1] FALSE  TRUE  TRUE
[1]  TRUE FALSE FALSE
[1]  TRUE  TRUE FALSE


### Ví dụ 5: Toán tử logic

In [30]:
a <- c(TRUE, FALSE, TRUE)
b <- c(FALSE, TRUE, TRUE)

print(a & b)    # [1] FALSE FALSE  TRUE

print(a | b)    # [1] TRUE TRUE TRUE

print(!a)       # [1] FALSE  TRUE FALSE

[1] FALSE FALSE  TRUE
[1] TRUE TRUE TRUE
[1] FALSE  TRUE FALSE



---

## **list**

Là một danh sách, có thể dùng để lưu các biến ở nhiều kiểu dữ liệu khác nhau. Để tạo 1 list, ta sử dụng hàm `list()`

In [31]:
list1 <- list(a = c(1, 2, 3),
              b = c("Apple", "Orange"),
              c = c(TRUE, FALSE))
print(list1)

$a
[1] 1 2 3

$b
[1] "Apple"  "Orange"

$c
[1]  TRUE FALSE



Để lấy các phần tử trong 1 list, ta sử dụng dấu $ như sau:

In [32]:
print(list1$a) # Kết quả: 1 2 3

[1] 1 2 3



---

## **factor**

Là một vector chuyên dùng để lưu trữ các biến định tính. Để tạo factor từ một vector, ta dùng hàm `factor()`

In [33]:
sex_vec <- c(
             "female", "female", "female", "male",
             "female", "male", "male", "female")
sex_fac <- factor(sex_vec)
print(sex_fac)

[1] female female female male   female male   male   female
Levels: female male


Ta có thể truy cập các phần tử của factor tương tự như vector

In [34]:
print(sex_fac[4])

[1] male
Levels: female male



---

## **matrix**
Là một mảng 2 chiều dùng để lưu trữ các dữ liệu có cùng kiểu với nhau. Để tạo một matrix, ta dùng hàm `matrix()`

In [35]:
matrix1 <- matrix(data = c(1, 2, 3, 4, 5, 6), ncol = 2)
print(matrix1)

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6


In [36]:
matrix2 <- matrix(data = c(1, 2, 3, 4, 5, 6), nrow = 2)
print(matrix2)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


In [37]:
matrix3 <- matrix(data = c(1, 2, 3, 4, 5, 6), ncol = 2, nrow = 2)
print(matrix3)

Warning message in matrix(data = c(1, 2, 3, 4, 5, 6), ncol = 2, nrow = 2):
"data length differs from size of matrix: [6 != 2 x 2]"


     [,1] [,2]
[1,]    1    3
[2,]    2    4


In [38]:
matrix4 <- matrix(data = c(1, 2, 3, 4, 5, 6), ncol = 3, nrow = 4)
print(matrix4)

     [,1] [,2] [,3]
[1,]    1    5    3
[2,]    2    6    4
[3,]    3    1    5
[4,]    4    2    6


In [39]:
matrix5 <- matrix(1:9, ncol = 3, nrow = 3)
print(matrix5)
print(matrix5[1, 1])

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9
[1] 1


In [40]:
matrix6 <- matrix(1:9, ncol = 3, nrow = 3, byrow = TRUE)
print(matrix6)

matrix7 <- matrix(1:9, ncol = 3, nrow = 3, byrow = FALSE)
print(matrix7)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9
